// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLRGNcRw7XC8SgmlsfvX1QnqzjKNMjaIc',
    appId: '1:149368587834:web:1fc74f51aed34f41751703',
    messagingSenderId: '149368587834',
    projectId: 'project-travel-29336',
    authDomain: 'project-travel-29336.firebaseapp.com',
    storageBucket: 'project-travel-29336.appspot.com',
    measurementId: 'G-FMDNKLZWLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwEjLboYMEDeg5Al-TERX2h9Ak8YABJjc',
    appId: '1:149368587834:android:08297345c814ec4d751703',
    messagingSenderId: '149368587834',
    projectId: 'project-travel-29336',
    storageBucket: 'project-travel-29336.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHcFLb88NyJ6Z-B-P9SXJRdiKjzynNS8Q',
    appId: '1:149368587834:ios:b8cea8b36ec76674751703',
    messagingSenderId: '149368587834',
    projectId: 'project-travel-29336',
    storageBucket: 'project-travel-29336.appspot.com',
    iosClientId: '149368587834-qanftocrhrgs00tje5us697r4ldbuq4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHcFLb88NyJ6Z-B-P9SXJRdiKjzynNS8Q',
    appId: '1:149368587834:ios:b8cea8b36ec76674751703',
    messagingSenderId: '149368587834',
    projectId: 'project-travel-29336',
    storageBucket: 'project-travel-29336.appspot.com',
    iosClientId: '149368587834-qanftocrhrgs00tje5us697r4ldbuq4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelProject',
  );
}
